spring:
  profiles:
    active: dev

server:
  port: 8888
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

#mybatis:
#  mapper-locations:
#    - classpath:mapping/*.xml


minio:
  endpoint: http://192.168.10.77:9000 #MinIO服务所在地址
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥